"""Shared enums and reason codes."""

from __future__ import annotations

from enum import Enum


class SignalDirection(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    EXIT = "exit"


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"


class OrderStatus(str, Enum):
    CREATED = "CREATED"
    RISK_PENDING = "RISK_PENDING"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"


class RiskDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REDUCED = "REDUCED"
    HALTED = "HALTED"


class RiskReasonCode(str, Enum):
    OK = "OK"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    LIVE_TRADING_DISABLED = "LIVE_TRADING_DISABLED"
    LIVE_GATING_INCOMPLETE = "LIVE_GATING_INCOMPLETE"
    DATA_STALE = "DATA_STALE"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    MIN_ORDER_SIZE = "MIN_ORDER_SIZE"
    PRECISION_INVALID = "PRECISION_INVALID"
    MAX_RISK_PER_TRADE = "MAX_RISK_PER_TRADE"
    MAX_POSITION_EXPOSURE = "MAX_POSITION_EXPOSURE"
    MAX_PORTFOLIO_EXPOSURE = "MAX_PORTFOLIO_EXPOSURE"
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    MAX_DRAWDOWN_REACHED = "MAX_DRAWDOWN_REACHED"
    MAX_CONSECUTIVE_LOSSES = "MAX_CONSECUTIVE_LOSSES"
    MAX_ORDER_FREQUENCY = "MAX_ORDER_FREQUENCY"
    CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER_OPEN"
    RISK_ENGINE_UNHEALTHY = "RISK_ENGINE_UNHEALTHY"
    MARKET_DATA_UNHEALTHY = "MARKET_DATA_UNHEALTHY"
    DATABASE_UNHEALTHY = "DATABASE_UNHEALTHY"
    RECONCILIATION_UNHEALTHY = "RECONCILIATION_UNHEALTHY"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_LIVE_APPROVAL = "INVALID_LIVE_APPROVAL"
    NEWS_EXTREME_UNCERTAINTY = "NEWS_EXTREME_UNCERTAINTY"
    SIZE_REDUCED_BY_NEWS = "SIZE_REDUCED_BY_NEWS"
    SIZE_REDUCED_BY_RISK = "SIZE_REDUCED_BY_RISK"
    SYMBOL_NOT_ALLOWED = "SYMBOL_NOT_ALLOWED"
    SHORT_SELLING_DISABLED = "SHORT_SELLING_DISABLED"
    LEVERAGE_NOT_ALLOWED = "LEVERAGE_NOT_ALLOWED"
    UNSUPPORTED_SIDE = "UNSUPPORTED_SIDE"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    ORDER_COOLDOWN = "ORDER_COOLDOWN"
    STOP_LOSS_REQUIRED = "STOP_LOSS_REQUIRED"
    MIN_REWARD_RISK = "MIN_REWARD_RISK"
    DAILY_TRADE_LIMIT = "DAILY_TRADE_LIMIT"


# Prompt-aligned alias
RiskRejectionReason = RiskReasonCode


class StrategyGovernanceStatus(str, Enum):
    DRAFT = "DRAFT"
    BACKTESTING = "BACKTESTING"
    VALIDATED = "VALIDATED"
    PAPER = "PAPER"
    TESTNET = "TESTNET"
    LIVE_APPROVED = "LIVE_APPROVED"
    RETIRED = "RETIRED"
