import type {
  BacktestReport,
  EquityPoint,
  Order,
  PortfolioSummary,
  Position,
  RiskEvent,
  SettingsView,
  Strategy,
  TradeSignal,
} from "./types";

const now = Date.now();

function hoursAgo(h: number): string {
  return new Date(now - h * 3600_000).toISOString();
}

function daysAgo(d: number): string {
  return new Date(now - d * 86_400_000).toISOString();
}

export const MOCK_PORTFOLIO: PortfolioSummary = {
  cash_balance: "7420.55",
  equity: "10185.40",
  realized_pnl: "312.18",
  unrealized_pnl: "185.40",
  daily_pnl: "64.22",
  peak_equity: "10450.00",
  drawdown: "0.0253",
  open_position_count: 2,
  consecutive_losses: 1,
  trading_mode: "paper",
  kill_switch_enabled: false,
  trading_paused: false,
  exchange_env: "paper",
};

export const MOCK_POSITIONS: Position[] = [
  {
    symbol: "BTC/USDT",
    quantity: "0.042",
    entry_price: "64250.00",
    current_price: "65810.25",
    unrealized_pnl: "65.53",
    realized_pnl: "120.00",
    opened_at: hoursAgo(18),
    strategy_name: "ema_trend",
    stop_loss: "62800.00",
    take_profit: "68500.00",
  },
  {
    symbol: "ETH/USDT",
    quantity: "1.25",
    entry_price: "3180.00",
    current_price: "3276.00",
    unrealized_pnl: "120.00",
    realized_pnl: "40.50",
    opened_at: hoursAgo(6),
    strategy_name: "ema_trend",
    stop_loss: "3050.00",
    take_profit: "3450.00",
  },
];

export const MOCK_EQUITY_CURVE: EquityPoint[] = Array.from({ length: 48 }, (_, i) => {
  const t = new Date(now - (47 - i) * 3600_000);
  const base = 10000 + i * 8 + Math.sin(i / 3) * 120;
  const peak = 10000 + i * 10;
  const equity = Math.max(9200, base);
  const dd = Math.max(0, (peak - equity) / peak);
  return {
    time: t.toISOString(),
    equity: equity.toFixed(2),
    drawdown: dd.toFixed(4),
  };
});

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_1001",
    client_order_id: "paper-1001",
    symbol: "BTC/USDT",
    side: "buy",
    order_type: "market",
    quantity: "0.042",
    filled_quantity: "0.042",
    price: null,
    average_fill_price: "64250.00",
    status: "FILLED",
    strategy_name: "ema_trend",
    risk_decision: "APPROVED",
    risk_reason_code: "OK",
    created_at: hoursAgo(18),
    updated_at: hoursAgo(18),
    fees: "2.70",
  },
  {
    id: "ord_1002",
    client_order_id: "paper-1002",
    symbol: "ETH/USDT",
    side: "buy",
    order_type: "limit",
    quantity: "1.25",
    filled_quantity: "1.25",
    price: "3180.00",
    average_fill_price: "3180.00",
    status: "FILLED",
    strategy_name: "ema_trend",
    risk_decision: "APPROVED",
    risk_reason_code: "OK",
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
    fees: "3.98",
  },
  {
    id: "ord_1003",
    client_order_id: "paper-1003",
    symbol: "BTC/USDT",
    side: "buy",
    order_type: "market",
    quantity: "0.10",
    filled_quantity: "0",
    price: null,
    average_fill_price: null,
    status: "REJECTED",
    strategy_name: "ema_trend",
    risk_decision: "REJECTED",
    risk_reason_code: "MAX_POSITION_EXPOSURE",
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
    fees: "0",
  },
  {
    id: "ord_1004",
    client_order_id: "paper-1004",
    symbol: "SOL/USDT",
    side: "sell",
    order_type: "limit",
    quantity: "12",
    filled_quantity: "0",
    price: "148.50",
    average_fill_price: null,
    status: "SUBMITTED",
    strategy_name: null,
    risk_decision: "APPROVED",
    risk_reason_code: "OK",
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
    fees: "0",
  },
];

export const MOCK_SIGNALS: TradeSignal[] = [
  {
    id: "sig_1",
    strategy_name: "ema_trend",
    strategy_version: "1.0.0",
    symbol: "BTC/USDT",
    timestamp: hoursAgo(0.5),
    direction: "buy",
    confidence: "0.72",
    entry_rationale: "Fast EMA crossed above slow EMA with rising momentum.",
    invalidation_condition: "Close below slow EMA on 1h.",
    suggested_stop: "64800.00",
    suggested_target: "67500.00",
    suggested_entry: "65810.00",
  },
  {
    id: "sig_2",
    strategy_name: "ema_trend",
    strategy_version: "1.0.0",
    symbol: "ETH/USDT",
    timestamp: hoursAgo(3),
    direction: "hold",
    confidence: "0.41",
    entry_rationale: "Trend intact; no fresh crossover.",
    invalidation_condition: "Break of prior swing low.",
    suggested_stop: "3050.00",
    suggested_target: "3450.00",
    suggested_entry: null,
  },
  {
    id: "sig_3",
    strategy_name: "ema_trend",
    strategy_version: "1.0.0",
    symbol: "BTC/USDT",
    timestamp: hoursAgo(8),
    direction: "exit",
    confidence: "0.66",
    entry_rationale: "Momentum fade after extended run.",
    invalidation_condition: "Reclaim of session high.",
    suggested_stop: null,
    suggested_target: null,
    suggested_entry: "65100.00",
  },
];

export const MOCK_RISK_EVENTS: RiskEvent[] = [
  {
    id: "risk_1",
    timestamp: hoursAgo(2),
    decision: "REJECTED",
    reason_code: "MAX_POSITION_EXPOSURE",
    message: "Requested size exceeds max position exposure (25%).",
    symbol: "BTC/USDT",
    strategy_name: "ema_trend",
    requested_quantity: "0.10",
    approved_quantity: null,
    order_id: "ord_1003",
  },
  {
    id: "risk_2",
    timestamp: hoursAgo(5),
    decision: "REDUCED",
    reason_code: "SIZE_REDUCED_BY_RISK",
    message: "Quantity reduced to satisfy max risk per trade (1%).",
    symbol: "ETH/USDT",
    strategy_name: "ema_trend",
    requested_quantity: "2.00",
    approved_quantity: "1.25",
    order_id: "ord_1002",
  },
  {
    id: "risk_3",
    timestamp: hoursAgo(12),
    decision: "APPROVED",
    reason_code: "OK",
    message: "All risk checks passed.",
    symbol: "BTC/USDT",
    strategy_name: "ema_trend",
    requested_quantity: "0.042",
    approved_quantity: "0.042",
    order_id: "ord_1001",
  },
  {
    id: "risk_4",
    timestamp: daysAgo(1),
    decision: "HALTED",
    reason_code: "KILL_SWITCH_ACTIVE",
    message: "Kill switch engaged — all new orders halted.",
    symbol: null,
    strategy_name: null,
    requested_quantity: null,
    approved_quantity: null,
    order_id: null,
  },
];

export const MOCK_STRATEGIES: Strategy[] = [
  {
    strategy_id: "ema_trend",
    name: "EMA Trend",
    version: "1.0.0",
    governance_status: "PAPER",
    description: "Dual EMA crossover with ATR-based stops. Deterministic, no LLM in path.",
    running: true,
    selected: true,
    paper_params: {
      fast_period: 12,
      slow_period: 26,
      atr_period: 14,
      atr_mult: 2.0,
    },
    symbols: ["BTC/USDT", "ETH/USDT"],
    timeframe: "1h",
  },
  {
    strategy_id: "mean_reversion_v0",
    name: "Mean Reversion v0",
    version: "0.2.0",
    governance_status: "BACKTESTING",
    description: "Experimental RSI mean-reversion scaffold — not paper-approved.",
    running: false,
    selected: false,
    paper_params: {
      rsi_period: 14,
      oversold: 30,
      overbought: 70,
    },
    symbols: ["BTC/USDT"],
    timeframe: "15m",
  },
  {
    strategy_id: "breakout_draft",
    name: "Range Breakout",
    version: "0.1.0",
    governance_status: "DRAFT",
    description: "Donchian-style breakout draft awaiting validation.",
    running: false,
    selected: false,
    paper_params: {
      lookback: 20,
      buffer_bps: 5,
    },
    symbols: ["BTC/USDT"],
    timeframe: "4h",
  },
  {
    strategy_id: "legacy_scalp",
    name: "Legacy Scalp",
    version: "0.9.0",
    governance_status: "RETIRED",
    description: "Retired after failing consecutive-loss governance gates.",
    running: false,
    selected: false,
    paper_params: {},
    symbols: ["BTC/USDT"],
    timeframe: "5m",
  },
];

export const MOCK_BACKTESTS: BacktestReport[] = [
  {
    run_id: "bt_demo_001",
    strategy_id: "ema_trend",
    status: "completed",
    created_at: daysAgo(2),
    config: {
      symbol: "BTC/USDT",
      timeframe: "1h",
      start: "2024-01-01",
      end: "2024-06-01",
      initial_cash: "10000",
    },
    metrics: {
      trade_count: 48,
      total_return: "0.1842",
      net_return: "1842.10",
      win_rate: "0.5417",
      profit_factor: "1.62",
      max_drawdown: "0.0921",
      sharpe: "1.24",
      sortino: "1.78",
      fees_paid: "126.40",
      slippage_cost: "38.20",
    },
    json_report: {
      run_id: "bt_demo_001",
      strategy_id: "ema_trend",
      metrics: {
        trade_count: 48,
        total_return: "0.1842",
        max_drawdown: "0.0921",
      },
    },
    markdown_report: [
      "# Backtest Report — ema_trend",
      "",
      "- Run ID: `bt_demo_001`",
      "- Trades: **48**",
      "- Total return: **0.1842**",
      "- Net P&L: **1842.10**",
      "- Win rate: **0.5417**",
      "- Profit factor: **1.62**",
      "- Max drawdown: **0.0921**",
      "- Sharpe: **1.24**",
      "- Sortino: **1.78**",
      "- Fees paid: **126.40**",
      "- Slippage cost: **38.20**",
      "",
    ].join("\n"),
    error: null,
  },
];

export const MOCK_SETTINGS: SettingsView = {
  trading_mode: "paper",
  live_trading_enabled: false,
  kill_switch_enabled: false,
  exchange_env: "paper",
  exchange_id: "binance",
  supported_symbols: ["BTC/USDT"],
  supported_timeframes: ["1m", "5m", "15m", "1h", "4h"],
  market_data_stale_seconds: 30,
  risk_limits: {
    max_risk_per_trade: "0.01",
    max_position_exposure: "0.25",
    max_portfolio_exposure: "0.80",
    max_open_positions: 3,
    max_daily_loss: "0.03",
    max_drawdown: "0.10",
    max_consecutive_losses: 5,
    max_orders_per_minute: 10,
    min_order_notional: "10",
    default_leverage: "1",
  },
};

/** Mutable demo state for mutating controls when backend is unavailable. */
export const demoState = {
  portfolio: { ...MOCK_PORTFOLIO },
  positions: [...MOCK_POSITIONS],
  orders: [...MOCK_ORDERS],
  signals: [...MOCK_SIGNALS],
  riskEvents: [...MOCK_RISK_EVENTS],
  strategies: MOCK_STRATEGIES.map((s) => ({ ...s, paper_params: { ...s.paper_params } })),
  backtests: [...MOCK_BACKTESTS],
  settings: {
    ...MOCK_SETTINGS,
    risk_limits: { ...MOCK_SETTINGS.risk_limits },
    supported_symbols: [...MOCK_SETTINGS.supported_symbols],
    supported_timeframes: [...MOCK_SETTINGS.supported_timeframes],
  },
  equityCurve: [...MOCK_EQUITY_CURVE],
};
